### ISSUE TITLE
Error: appworkshop_346110.acf not found

### ISSUE THREAD

**Issue by Hr46ph** [r15ch13/arkcluster#11]
I had to create some directories that were missing. I'm not sure why they aren't simply being created because there are no permissions issues.

`./<volume name>/default` didn't exist, so arkmanager complains it cannot find arkmanager.cfg. Once created, the file is placed and complaints stop.

A directory referred to as `/home/steam/Steam/steamapps/workshop` doesn't exist. It translates to `./<volume name>/steam/steamapps/workshop`. I created it, but then it complains about this:
`Error: appworkshop_346110.acf not found at /home/steam/Steam/steamapps/workshop`

There's nothing else in the logs.

Since UID/GID 1000 is already in use, I created a steam user with UID/GID 2000 on the docker host. I created its home dir, chowned 2000:2000 and added steam to the docker group. Steam homedir on the docker host is at `/data/docker-data/ark-server`.

The steam user is effectively root through that, I'm aware (I can change it later if need be).
I tried to run `docker-compose up` as root but that doesn't change the error below and that the ark server isn't installing.

Even though it says its running, its not:

```
[steam@atlantis ~]$ du -sBM *
1M	cluster
1M	docker-compose.yaml
1M	fjordur
1M	svartalfheim
```
I'll muck around inside the containers to see if I can make it work that way.

Below is the complete docker-compose output.
```
# docker-compose up
[+] Running 2/0
 ✔ Container ark-server-svartalfheim-1  Created                                                                                                     0.0s 
 ✔ Container ark-server-fjordur-1       Created                                                                                                     0.0s 
Attaching to ark-server-fjordur-1, ark-server-svartalfheim-1
ark-server-svartalfheim-1  | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
ark-server-svartalfheim-1  | *** Running /etc/my_init.d/10_syslog-ng.init...
ark-server-svartalfheim-1  | Jul 18 20:33:14 bca4883b4bb9 syslog-ng[13]: syslog-ng starting up; version='3.35.1'
ark-server-fjordur-1       | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
ark-server-fjordur-1       | *** Running /etc/my_init.d/10_syslog-ng.init...
ark-server-fjordur-1       | Jul 18 20:33:15 b0e74327a81f syslog-ng[13]: syslog-ng starting up; version='3.35.1'
ark-server-svartalfheim-1  | *** Booting runit daemon...
ark-server-svartalfheim-1  | *** Runit started as PID 21
ark-server-svartalfheim-1  | 2023-07-18T20:33:15Z: ###########################################################################
ark-server-svartalfheim-1  | Jul 18 20:33:15 bca4883b4bb9 cron[25]: (CRON) INFO (pidfile fd = 3)
ark-server-svartalfheim-1  | Jul 18 20:33:15 bca4883b4bb9 cron[25]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
ark-server-svartalfheim-1  | 2023-07-18T20:33:15Z: # Started  - Tue Jul 18 08:33:15 PM CEST 2023
ark-server-svartalfheim-1  | 2023-07-18T20:33:15Z: # Server   - PBG Cluster Svartalfheim
ark-server-svartalfheim-1  | 2023-07-18T20:33:16Z: # Cluster  - pbgcl1
ark-server-svartalfheim-1  | 2023-07-18T20:33:16Z: # User     - 2000
ark-server-svartalfheim-1  | 2023-07-18T20:33:16Z: # Group    - 2000
ark-server-svartalfheim-1  | 2023-07-18T20:33:16Z: ###########################################################################
ark-server-svartalfheim-1  | 2023-07-18T20:33:16Z: Setting timezone to Europe/Amsterdam ...
ark-server-svartalfheim-1  | 2023-07-18T20:33:16Z: ###########################################################################
ark-server-svartalfheim-1  | 2023-07-18T20:33:16Z: No game files found. Installing...
ark-server-svartalfheim-1  | Attempting to drop privileges; re-running as steam
ark-server-fjordur-1       | *** Booting runit daemon...
ark-server-fjordur-1       | *** Runit started as PID 23
ark-server-fjordur-1       | 2023-07-18T20:33:16Z: ###########################################################################
ark-server-fjordur-1       | Jul 18 20:33:16 b0e74327a81f cron[28]: (CRON) INFO (pidfile fd = 3)
ark-server-fjordur-1       | 2023-07-18T20:33:16Z: # Started  - Tue Jul 18 08:33:16 PM CEST 2023
ark-server-svartalfheim-1  | Running command 'install' for instance 'main'
ark-server-fjordur-1       | 2023-07-18T20:33:16Z: # Server   - PBG Cluster Fjordur
ark-server-fjordur-1       | Jul 18 20:33:16 b0e74327a81f cron[28]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
ark-server-svartalfheim-1  | Installing ARK server
ark-server-fjordur-1       | 2023-07-18T20:33:16Z: # Cluster  - pbgcl1
ark-server-svartalfheim-1  |  ...  
ark-server-svartalfheim-1  | .
ark-server-fjordur-1       | 2023-07-18T20:33:16Z: # User     - 2000
ark-server-fjordur-1       | 2023-07-18T20:33:16Z: # Group    - 2000
ark-server-fjordur-1       | 2023-07-18T20:33:16Z: ###########################################################################
ark-server-fjordur-1       | 2023-07-18T20:33:16Z: Setting timezone to Europe/Amsterdam ...
ark-server-fjordur-1       | 2023-07-18T20:33:16Z: ###########################################################################
ark-server-fjordur-1       | 2023-07-18T20:33:16Z: No game files found. Installing...
ark-server-fjordur-1       | Attempting to drop privileges; re-running as steam
ark-server-fjordur-1       | Running command 'install' for instance 'main'
ark-server-fjordur-1       | Installing ARK server
ark-server-fjordur-1       |  ...  
ark-server-fjordur-1       | .
ark-server-svartalfheim-1  | .
ark-server-fjordur-1       | .
...
lots more of those ...
...
ark-server-svartalfheim-1  | 
ark-server-svartalfheim-1  | 2023-07-18T20:33:34Z: ###########################################################################
ark-server-svartalfheim-1  | 2023-07-18T20:33:34Z: Installing Mods ...
ark-server-svartalfheim-1  | Attempting to drop privileges; re-running as steam
ark-server-fjordur-1       | 
ark-server-fjordur-1       | 2023-07-18T20:33:34Z: ###########################################################################
ark-server-fjordur-1       | 2023-07-18T20:33:34Z: Installing Mods ...
ark-server-svartalfheim-1  | Running command 'checkmodupdate' for instance 'main'
ark-server-svartalfheim-1  | Error: appworkshop_346110.acf not found at /home/steam/Steam/steamapps/workshop
ark-server-svartalfheim-1  | All mods are up to date
ark-server-svartalfheim-1  | 2023-07-18T20:33:34Z: ###########################################################################
ark-server-svartalfheim-1  | 2023-07-18T20:33:34Z: Launching ark server ...
ark-server-fjordur-1       | Attempting to drop privileges; re-running as steam
ark-server-fjordur-1       | Running command 'checkmodupdate' for instance 'main'
ark-server-svartalfheim-1  | Attempting to drop privileges; re-running as steam
ark-server-fjordur-1       | Error: appworkshop_346110.acf not found at /home/steam/Steam/steamapps/workshop
ark-server-fjordur-1       | All mods are up to date
ark-server-fjordur-1       | 2023-07-18T20:33:34Z: ###########################################################################
ark-server-fjordur-1       | 2023-07-18T20:33:34Z: Launching ark server ...
ark-server-svartalfheim-1  | Running command 'start' for instance 'main'
ark-server-svartalfheim-1  | Checking for updates before starting
ark-server-svartalfheim-1  | Checking for update; PID: 283
ark-server-fjordur-1       | Attempting to drop privileges; re-running as steam
ark-server-fjordur-1       | Running command 'start' for instance 'main'
ark-server-fjordur-1       | Checking for updates before starting
ark-server-fjordur-1       | Checking for update; PID: 285
ark-server-svartalfheim-1  | Your server is already up to date! The most recent version is .
ark-server-svartalfheim-1  | 
ark-server-svartalfheim-1  | The server is starting...
ark-server-svartalfheim-1  | 
ark-server-svartalfheim-1  | 
ark-server-svartalfheim-1  | The server is now running, and should be up within 10 minutes
ark-server-svartalfheim-1  | 2023-07-18T20:33:52Z: ###########################################################################
ark-server-svartalfheim-1  | 2023-07-18T20:33:52Z: Running ... (waiting for INT/TERM signal)
ark-server-fjordur-1       | Your server is already up to date! The most recent version is .
ark-server-fjordur-1       | 
ark-server-fjordur-1       | The server is starting...
ark-server-fjordur-1       | 
ark-server-fjordur-1       | 
ark-server-fjordur-1       | The server is now running, and should be up within 10 minutes
ark-server-fjordur-1       | 2023-07-18T20:33:52Z: ###########################################################################
ark-server-fjordur-1       | 2023-07-18T20:33:52Z: Running ... (waiting for INT/TERM signal)
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Stopping 2/2
 ✔ Container ark-server-svartalfheim-1  Stopped                                                                                                     2.2s 
 ✔ Container ark-server-fjordur-1       Stopped                                                                                                     2.1s 
canceled
```
The docker-compose.yaml
```
# cat docker-compose.yaml 
version: "3.8"

services:
  fjordur:
    image: r15ch13/arkcluster:latest
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "0 */3 * * *"
      CRON_AUTO_BACKUP: "0 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 2000
      GROUP_ID: 2000
      TZ: "Europe/Amsterdam"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Fjordur"
      SESSION_NAME: "PBG Cluster Fjordur"
      MAX_PLAYERS: 15
      RCON_ENABLE: "True"
      QUERY_PORT: 15000
      GAME_PORT: 15002
      RCON_PORT: 15003
      SERVER_PVE: "True"
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "blabla"
      SPECTATOR_PASSWORD: "blabla"
      MODS: ""
      CLUSTER_ID: "pbgcl1"
      GAME_USERSETTINGS_INI_PATH: "/cluster/pbgcl1.GameUserSettings.ini"
      GAME_INI_PATH: "/cluster/pbgcl1.Game.ini"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - ./fjordur:/ark
      - ./cluster:/cluster
    ports:
      - "15000-15003:15000-15003/udp"

  svartalfheim:
    image: r15ch13/arkcluster:latest
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 2000
      GROUP_ID: 2000
      TZ: "Europe/Amsterdam"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Svartalfheim"
      SESSION_NAME: "PBG Cluster Svartalfheim"
      MAX_PLAYERS: 15
      RCON_ENABLE: "False"
      QUERY_PORT: 15010
      GAME_PORT: 15012
      RCON_PORT: 15013
      SERVER_PVE: "True"
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "blabla"
      SPECTATOR_PASSWORD: "blabla"
      MODS: ""
      CLUSTER_ID: "pbgcl1"
      GAME_USERSETTINGS_INI_PATH: "/cluster/pbgcl1.GameUserSettings.ini"
      GAME_INI_PATH: "/cluster/pbgcl1.Game.ini"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - ./svartalfheim:/ark
      - ./cluster:/cluster
    ports:
      - "15010-15013:15010-15013/udp"
```
If you have any ideas I'd love to hear them.

Thanks!
