### ISSUE TITLE
Is my network bad?

### ISSUE THREAD

**Issue by alec121100** [r15ch13/arkcluster#17]
Hello, I just try to make Cluster out of 7 Maps. I edited the compose.yml for my cluster.

```yml
version: "3"

services:
  island:
    image: r15ch13/arkcluster:latest
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "0 */3 * * *"
      CRON_AUTO_BACKUP: "0 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: "UTC"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "TheIsland"
      SESSION_NAME: "ARK Cluster TheIsland"
      MAX_PLAYERS: 15
      RCON_ENABLE: "True"
      QUERY_PORT: 15000
      GAME_PORT: 15002
      RCON_PORT: 15003
      SERVER_PVE: "False"
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: ""
      SPECTATOR_PASSWORD: ""
      MODS: "1650069767,924933745,895711211,1775666168,1404697612,2017186718,1814953878,1591643730,1941328406,630601751,1609138312,1379153273,1428596566,1934081600,793605978"
      CLUSTER_ID: ""
      GAME_USERSETTINGS_INI_PATH: "/cluster/myclusterid.GameUserSettings.ini"
      GAME_INI_PATH: "/cluster/myclusterid.Game.ini"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /home/ark/data_island:/ark
      - /home/ark/cluster:/cluster
    ports:
      - "15000-15003:15000-15003/udp"

  ragnarok:
    image: r15ch13/arkcluster:latest
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: "UTC"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Ragnarok"
      SESSION_NAME: "ARK Cluster Ragnarok "
      MAX_PLAYERS: 15
      RCON_ENABLE: "False"
      QUERY_PORT: 15010
      GAME_PORT: 15012
      RCON_PORT: 15013
      SERVER_PVE: "True"
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: ""
      SPECTATOR_PASSWORD: ""
      MODS: "1650069767,924933745,895711211,1775666168,1404697612,2017186718,1814953878,1591643730,1941328406,630601751,1609138312,1379153273,1428596566,1934081600,793605978"
      CLUSTER_ID: ""
      GAME_USERSETTINGS_INI_PATH: "/cluster/myclusterid.GameUserSettings.ini"
      GAME_INI_PATH: "/cluster/myclusterid.Game.ini"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /home/ark/data_ragnarok:/ark
      - /home/ark/cluster:/cluster
    ports:
      - "15010-15013:15010-15013/udp"

  fjordur:
    image: r15ch13/arkcluster:latest
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: "UTC"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Fjordur"
      SESSION_NAME: "ARK Cluster Fjordur "
      MAX_PLAYERS: 15
      RCON_ENABLE: "False"
      QUERY_PORT: 15020
      GAME_PORT: 15022
      RCON_PORT: 15023
      SERVER_PVE: "True"
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: ""
      SPECTATOR_PASSWORD: ""
      MODS: "1650069767,924933745,895711211,1775666168,1404697612,2017186718,1814953878,1591643730,1941328406,630601751,1609138312,1379153273,1428596566,1934081600,793605978"
      CLUSTER_ID: ""
      GAME_USERSETTINGS_INI_PATH: "/cluster/myclusterid.GameUserSettings.ini"
      GAME_INI_PATH: "/cluster/myclusterid.Game.ini"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /home/ark/data_fjordur:/ark
      - /home/ark/cluster:/cluster
    ports:
      - "15020-15023:15020-15023/udp"

  center:
    image: r15ch13/arkcluster:latest
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: "UTC"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "TheCenter"
      SESSION_NAME: "ARK Cluster Center "
      MAX_PLAYERS: 15
      RCON_ENABLE: "False"
      QUERY_PORT: 15030
      GAME_PORT: 15032
      RCON_PORT: 15033
      SERVER_PVE: "True"
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: ""
      SPECTATOR_PASSWORD: ""
      MODS: "1650069767,924933745,895711211,1775666168,1404697612,2017186718,1814953878,1591643730,1941328406,630601751,1609138312,1379153273,1428596566,1934081600,793605978"
      CLUSTER_ID: ""
      GAME_USERSETTINGS_INI_PATH: "/cluster/myclusterid.GameUserSettings.ini"
      GAME_INI_PATH: "/cluster/myclusterid.Game.ini"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /home/ark/data_center:/ark
      - /home/ark/cluster:/cluster
    ports:
      - "15030-15033:15030-15033/udp"

  aberration:
    image: r15ch13/arkcluster:latest
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: "UTC"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Aberration_P"
      SESSION_NAME: "ARK Cluster Aberration "
      MAX_PLAYERS: 15
      RCON_ENABLE: "False"
      QUERY_PORT: 15040
      GAME_PORT: 15042
      RCON_PORT: 15043
      SERVER_PVE: "True"
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: ""
      SPECTATOR_PASSWORD: ""
      MODS: "1650069767,924933745,895711211,1775666168,1404697612,2017186718,1814953878,1591643730,1941328406,630601751,1609138312,1379153273,1428596566,1934081600,793605978"
      CLUSTER_ID: ""
      GAME_USERSETTINGS_INI_PATH: "/cluster/myclusterid.GameUserSettings.ini"
      GAME_INI_PATH: "/cluster/myclusterid.Game.ini"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /home/ark/data_aberration:/ark
      - /home/ark/cluster:/cluster
    ports:
      - "15040-15043:15040-15043/udp"

  crystal:
    image: r15ch13/arkcluster:latest
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: "UTC"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "CrystalIsles"
      SESSION_NAME: "ARK Cluster Crystalmeth "
      MAX_PLAYERS: 15
      RCON_ENABLE: "False"
      QUERY_PORT: 15050
      GAME_PORT: 15052
      RCON_PORT: 15053
      SERVER_PVE: "True"
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: ""
      SPECTATOR_PASSWORD: ""
      MODS: "1650069767,924933745,895711211,1775666168,1404697612,2017186718,1814953878,1591643730,1941328406,630601751,1609138312,1379153273,1428596566,1934081600,793605978"
      CLUSTER_ID: ""
      GAME_USERSETTINGS_INI_PATH: "/cluster/myclusterid.GameUserSettings.ini"
      GAME_INI_PATH: "/cluster/myclusterid.Game.ini"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /home/ark/data_crystal:/ark
      - /home/ark/cluster:/cluster
    ports:
      - "15050-15053:15050-15053/udp"

  genesis2:
    image: r15ch13/arkcluster:latest
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: "UTC"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Gen2"
      SESSION_NAME: "ARK Cluster Genesis 2 "
      MAX_PLAYERS: 15
      RCON_ENABLE: "False"
      QUERY_PORT: 15060
      GAME_PORT: 15062
      RCON_PORT: 15063
      SERVER_PVE: "True"
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: ""
      SPECTATOR_PASSWORD: ""
      MODS: "1650069767,924933745,895711211,1775666168,1404697612,2017186718,1814953878,1591643730,1941328406,630601751,1609138312,1379153273,1428596566,1934081600,793605978"
      CLUSTER_ID: ""
      GAME_USERSETTINGS_INI_PATH: "/cluster/myclusterid.GameUserSettings.ini"
      GAME_INI_PATH: "/cluster/myclusterid.Game.ini"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /home/ark/data_gen2:/ark
      - /home/ark/cluster:/cluster
    ports:
      - "15060-15063:15060-15063/udp"


volumes:
  data_island:
  data_ragnarok:
  data_fjordur:
  data_center:
  data_aberration:
  data_crystal:
  data_gen2:
  cluster:
```

Of course I have the passwords and clusterid set. 
Does this compose looks right to you? There are no errors. The paths for the volumes are existent but I just put the .ini files in it. Is that right?

Beside of that, I composed that up for about 2 hours ago and there is still no playable server yet. My downstream is maximized and I've shut down all containers but one for a higher download. But still no progress that I could see. Am I do something wrong? And how do I install mods? With the arkmanager?
