### ISSUE TITLE
New to this question

### ISSUE THREAD

**Issue by bchilton9** [r15ch13/arkcluster#5]
How do I set options like TamingSpeedMultiplier?

and it says the stop is a clean stop. dose that mean I can stop the container to shut off the server?

Thank you

**Comment by zokradonh** [comment]
`docker stop` stops the server cleanly and then stops the container.

You set all settings like `TamingSpeedMultiplier` in the Game.ini and GameUserSettings.ini files in the volume. Do you know how to access the volume?

**Comment by bchilton9** [comment]
Thank you.

The challenge I’m having now is in the GameUserSettings.Ini the settings I have changed are staying there except TamingSpeedMultiplier. When I add it start the server, stop the server and open the ini the other changes are still there but TamingSpeedMultiplier=5 is completely gone. I’m thinking ark manager is changing it but I don’t know how to change it in ark manager.

Also I have 9 containers (all maps but gen2) 6 of them are working fine. Genesis, crystal isles, and extension show in the logs that they have come on but steam can not find the server. Are there any special steps to get them working?

Log (all 3 containers look the same):
``` Copying ARK tribute tribe files 

 Copying mod persistent info 

'/ark/server/ShooterGame/Saved/SaveGames' -> '/ark/backup/2021-07-28_20.56.06/SaveGames'

'/ark/server/ShooterGame/Saved/SaveGames/DeathInventoryKeeperArchive.sav' -> '/ark/backup/2021-07-28_20.56.06/SaveGames/DeathInventoryKeeperArchive.sav'

 Copying GameUserSettings.ini [   OK   ]

 Copying Game.ini [   OK   ]

 Compressing Backup [   OK   ]

 Created Backup:  main.2021-07-28_20.56.06.tar.bz2

Attempting to drop privileges; re-running as steam

Running command 'stop' for instance 'main'

The server is already stopped

*** Shutting down runit daemon (PID 20)...

*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...

Jul 28 20:56:11 f13de1513142 syslog-ng[13]: syslog-ng shutting down; version='3.13.2'

*** Init system aborted.

*** Killing all processes...

*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...

*** Running /etc/my_init.d/10_syslog-ng.init...

Jul 29 07:53:15 f13de1513142 syslog-ng[14]: syslog-ng starting up; version='3.13.2'

*** Booting runit daemon...

*** Runit started as PID 23

2021-07-29T07:53:16Z: ###########################################################################

2021-07-29T07:53:16Z: # Started  - Thu Jul 29 07:53:16 MDT 2021

Jul 29 07:53:16 f13de1513142 cron[28]: (CRON) INFO (pidfile fd = 3)

2021-07-29T07:53:16Z: # Server   - SERVER Genesis

Jul 29 07:53:16 f13de1513142 cron[28]: (CRON) INFO (Skipping @reboot jobs -- not system startup)

2021-07-29T07:53:16Z: # Cluster  - SERVER

2021-07-29T07:53:16Z: # User     - 1000

2021-07-29T07:53:16Z: # Group    - 100

2021-07-29T07:53:16Z: ###########################################################################

2021-07-29T07:53:16Z: Setting timezone to America/Denver ...

2021-07-29T07:53:26Z: ###########################################################################

2021-07-29T07:53:26Z: Creating Backup ...

Attempting to drop privileges; re-running as steam

Running command 'backup' for instance 'main'

 Saved arks directory is /ark/server/ShooterGame/Saved/SavedArks

 Copying ARK world file (Genesis) [   OK   ]

 Copying ARK profile files

 Copying ARK tribe files 

 Copying ARK tribute tribe files 

 Copying mod persistent info 

'/ark/server/ShooterGame/Saved/SaveGames' -> '/ark/backup/2021-07-29_07.53.26/SaveGames'

'/ark/server/ShooterGame/Saved/SaveGames/DeathInventoryKeeperArchive.sav' -> '/ark/backup/2021-07-29_07.53.26/SaveGames/DeathInventoryKeeperArchive.sav'

 Copying GameUserSettings.ini [   OK   ]

 Copying Game.ini [   OK   ]

 Compressing Backup [   OK   ]

 Created Backup:  main.2021-07-29_07.53.26.tar.bz2

2021-07-29T07:53:30Z: ###########################################################################

2021-07-29T07:53:30Z: Installing Mods ...

Attempting to drop privileges; re-running as steam

Running command 'installmods' for instance 'main'

Downloading mod 1404697612 ...  -/|\-/|\-/|\- Mod 1404697612 downloaded

Copying files to /ark/staging/Mods/1404697612

Mod 1404697612 installed

Downloading mod 1568516940 ...  -/|\-/|\- Mod 1568516940 downloaded

Copying files to /ark/staging/Mods/1568516940

Mod 1568516940 installed

Downloading mod 1837445660 ...  -/|\-/|\ Mod 1837445660 downloaded

Copying files to /ark/staging/Mods/1837445660

Mod 1837445660 installed

Downloading mod 1999447172 ...  -/|\-/|\- Mod 1999447172 downloaded

Copying files to /ark/staging/Mods/1999447172

Mod 1999447172 installed

Downloading mod 2227091285 ...  -/|\-/|\-/ Mod 2227091285 downloaded

Copying files to /ark/staging/Mods/2227091285

Mod 2227091285 installed

Downloading mod 618916953 ...  -/|\-/|\- Mod 618916953 downloaded

Copying files to /ark/staging/Mods/618916953

Mod 618916953 installed

Downloading mod 741203089 ...  -/|\-/|\- Mod 741203089 downloaded

Copying files to /ark/staging/Mods/741203089

Mod 741203089 installed

Downloading mod 791674340 ...  -/|\-/|\- Mod 791674340 downloaded

Copying files to /ark/staging/Mods/791674340

Mod 791674340 installed

Downloading mod 797686039 ...  -/|\-/|\ Mod 797686039 downloaded

Copying files to /ark/staging/Mods/797686039

Mod 797686039 installed

Downloading mod 880871931 ...  -/|\-/|\- Mod 880871931 downloaded

Copying files to /ark/staging/Mods/880871931

Mod 880871931 installed

Downloading mod 893834064 ...  -/|\-/|\- Mod 893834064 downloaded

Copying files to /ark/staging/Mods/893834064

Mod 893834064 installed

Downloading mod 924933745 ...  -/|\-/|\- Mod 924933745 downloaded

Copying files to /ark/staging/Mods/924933745

Mod 924933745 installed

2021-07-29T07:54:32Z: ###########################################################################

2021-07-29T07:54:32Z: Launching ark server ...

Attempting to drop privileges; re-running as steam

Running command 'start' for instance 'main'

Checking for updates before starting

Checking for update; PID: 1154

Your server is already up to date! The most recent version is 7101527.

The server is starting...

The server is now running, and should be up within 10 minutes

2021-07-29T07:54:42Z: ###########################################################################

2021-07-29T07:54:42Z: Running ... (waiting for INT/TERM signal)

Jul 29 08:15:01 f13de1513142 CRON[1459]: (steam) CMD (bash -l -c 'arkmanager backup >> /ark/log/ark-backup.log 2>&1')

Jul 29 08:17:01 f13de1513142 CRON[1503]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly) 
```


Here is my docker:

```

version: "3.5"

services:
  island:
    image: r15ch13/arkcluster:latest
    restart: "no"
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "0 */3 * * *"
      CRON_AUTO_BACKUP: "0 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 100
      TZ: "America/Denver"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "TheIsland"
      SESSION_NAME: "SERVER TheIsland"
      MAX_PLAYERS: 15
      SERVER_PVE: "True"
      RCON_ENABLE: "True"
      RCON_PORT: 32330
      GAME_PORT: 17777
      QUERY_PORT: 27015
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "PASSWORD"
      SPECTATOR_PASSWORD: "PASSWORD"
      MODS: "797686039,1568516940,924933745,1404697612,618916953,2227091285,893834064,791674340,1837445660,1999447172,741203089,880871931"
      CLUSTER_ID: "SERVER"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/theisland:/ark
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/cluster:/cluster
    ports:
      - "32330:32330/tcp"
      - "17777:17777/udp"
      - "17778:17778/udp"
      - "27015:27015/udp"

  valguero:
    image: r15ch13/arkcluster:latest
    restart: "no"
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 100
      TZ: "America/Denver"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Valguero_P"
      SESSION_NAME: “SERVER Valguero"
      MAX_PLAYERS: 15
      SERVER_PVE: "True"
      RCON_ENABLE: "False"
      RCON_PORT: 32331
      GAME_PORT: 17779
      QUERY_PORT: 27016
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "PASSWORD"
      SPECTATOR_PASSWORD: "PASSWORD"
      MODS: "797686039,1568516940,924933745,1404697612,618916953,2227091285,893834064,791674340,1837445660,1999447172,741203089,880871931"
      CLUSTER_ID: "SERVER"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/valguero:/ark
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/cluster:/cluster
    ports:
      - "32331:32331/tcp"
      - "17779:17779/udp"
      - "17780:17780/udp"
      - "27016:27016/udp"

  scorched:
    image: r15ch13/arkcluster:latest
    restart: "no"
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 100
      TZ: "America/Denver"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "ScorchedEarth_P"
      SESSION_NAME: "SERVER Scorched Earth"
      MAX_PLAYERS: 15
      SERVER_PVE: "True"
      RCON_ENABLE: "False"
      RCON_PORT: 32332
      GAME_PORT: 17781
      QUERY_PORT: 27017
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "PASSWORD"
      SPECTATOR_PASSWORD: "PASSWORD"
      MODS: "797686039,1568516940,924933745,1404697612,618916953,2227091285,893834064,791674340,1837445660,1999447172,741203089,880871931"
      CLUSTER_ID: "SERVER"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/scorchedearth:/ark
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/cluster:/cluster
    ports:
      - "32332:32332/tcp"
      - "17781:17781/udp"
      - "17782:17782/udp"
      - "27017:27017/udp"

  center:
    image: r15ch13/arkcluster:latest
    restart: "no"
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 100
      TZ: "America/Denver"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "TheCenter"
      SESSION_NAME: "SERVER The Center"
      MAX_PLAYERS: 15
      SERVER_PVE: "True"
      RCON_ENABLE: "False"
      RCON_PORT: 32333
      GAME_PORT: 17783
      QUERY_PORT: 27018
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "PASSWORD"
      SPECTATOR_PASSWORD: "PASSWORD"
      MODS: "797686039,1568516940,924933745,1404697612,618916953,2227091285,893834064,791674340,1837445660,1999447172,741203089,880871931"
      CLUSTER_ID: "SERVER"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/thecenter:/ark
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/cluster:/cluster
    ports:
      - "32333:32333/tcp"
      - "17783:17783/udp"
      - "17784:17784/udp"
      - "27018:27018/udp"

  ragnarok:
    image: r15ch13/arkcluster:latest
    restart: "no"
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 100
      TZ: "America/Denver"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Ragnarok"
      SESSION_NAME: “SERVER Ragnarok"
      MAX_PLAYERS: 15
      SERVER_PVE: "True"
      RCON_ENABLE: "False"
      RCON_PORT: 32334
      GAME_PORT: 17785
      QUERY_PORT: 27019
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "PASSWORD"
      SPECTATOR_PASSWORD: "PASSWORD"
      MODS: "797686039,1568516940,924933745,1404697612,618916953,2227091285,893834064,791674340,1837445660,1999447172,741203089,880871931"
      CLUSTER_ID: "SERVER"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/ragnarok:/ark
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/cluster:/cluster
    ports:
      - "32334:32334/tcp"
      - "17785:17785/udp"
      - "17786:17786/udp"
      - "27019:27019/udp"

  aberration:
    image: r15ch13/arkcluster:latest
    restart: "no"
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 100
      TZ: "America/Denver"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Aberration_P"
      SESSION_NAME: "SERVER Aberration"
      MAX_PLAYERS: 15
      SERVER_PVE: "True"
      RCON_ENABLE: "False"
      RCON_PORT: 32335
      GAME_PORT: 17787
      QUERY_PORT: 27020
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "PASSWORD"
      SPECTATOR_PASSWORD: "PASSWORD"
      MODS: "797686039,1568516940,924933745,1404697612,618916953,2227091285,893834064,791674340,1837445660,1999447172,741203089,880871931"
      CLUSTER_ID: "SERVER"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/aberration:/ark
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/cluster:/cluster
    ports:
      - "32335:32335/tcp"
      - "17787:17787/udp"
      - "17788:17788/udp"
      - "27020:27020/udp"

  extinction:
    image: r15ch13/arkcluster:latest
    restart: "no"
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 100
      TZ: "America/Denver"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Extinction"
      SESSION_NAME: "SERVER Extinction"
      MAX_PLAYERS: 15
      SERVER_PVE: "True"
      RCON_ENABLE: "False"
      RCON_PORT: 32336
      GAME_PORT: 17789
      QUERY_PORT: 27021
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "PASSWORD"
      SPECTATOR_PASSWORD: "PASSWORD"
      MODS: "797686039,1568516940,924933745,1404697612,618916953,2227091285,893834064,791674340,1837445660,1999447172,741203089,880871931"
      CLUSTER_ID: "SERVER"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/extinction:/ark
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/cluster:/cluster
    ports:
      - "32336:32336/tcp"
      - "17789:17789/udp"
      - "17790:17790/udp"
      - "27021:27021/udp"

  genesis:
    image: r15ch13/arkcluster:latest
    restart: "no"
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 100
      TZ: "America/Denver"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Genesis"
      SESSION_NAME: "SERVER Genesis"
      MAX_PLAYERS: 15
      SERVER_PVE: "True"
      RCON_ENABLE: "False"
      RCON_PORT: 32337
      GAME_PORT: 17791
      QUERY_PORT: 27022
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "PASSWORD"
      SPECTATOR_PASSWORD: "PASSWORD"
      MODS: "797686039,1568516940,924933745,1404697612,618916953,2227091285,893834064,791674340,1837445660,1999447172,741203089,880871931"
      CLUSTER_ID: "SERVER"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/genesis:/ark
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/cluster:/cluster
    ports:
      - "32337:32337/tcp"
      - "17791:17791/udp"
      - "17792:17792/udp"
      - "27022:27022/udp"

  crystalisles:
    image: r15ch13/arkcluster:latest
    restart: "no"
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 100
      TZ: "America/Denver"
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "CrystalIsles"
      SESSION_NAME: "SERVER Crystal Isles"
      MAX_PLAYERS: 15
      SERVER_PVE: "True"
      RCON_ENABLE: "False"
      RCON_PORT: 32338
      GAME_PORT: 17793
      QUERY_PORT: 27023
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "PASSWORD"
      SPECTATOR_PASSWORD: "PASSWORD"
      MODS: "797686039,1568516940,924933745,1404697612,618916953,2227091285,893834064,791674340,1837445660,1999447172,741203089,880871931"
      CLUSTER_ID: "SERVER"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/crystalisles:/ark
      - /srv/dev-disk-by-label-media/appdata/.config/arkcluster/cluster:/cluster
    ports:
      - "32338:32338/tcp"
      - "17793:17793/udp"
      - "17794:17794/udp"
      - "27023:27023/udp"

volumes:
  server_island:
  server_valguero:
  server_scorched:
  server_center:
  server_ragnarok:
  server_aberration:
  server_extinction:
  server_genesis:
  server_crystalisles:
  cluster:

```

I have tried deleting the container and folder for the 3 maps not working and restarting them. I get the logs that the server files/mods are downloading. And still cant find the server in steam.

Thank you.
